<a href="https://colab.research.google.com/github/alfredo030515/My-Projects/blob/Machine-Learning/Regresi%C3%B3n_Log%C3%ADstica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Regresión Logística**

In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.multioutput import MultiOutputClassifier

def cargar_datos(ruta):
    df = pd.read_csv(ruta, sep=r'\s+', header=None, skiprows=1).to_numpy()
    datos = np.array([fila[:10] for fila in df])
    clase = np.array([fila[-3:] for fila in df])
    return datos, clase

def codificar_datos(datos):
    label_encoders = []
    for i in range(datos.shape[1]):
        if isinstance(datos[0, i], str):
            le = LabelEncoder()
            datos[:, i] = le.fit_transform(datos[:, i])
            label_encoders.append(le)
        else:
            label_encoders.append(None)
    datos = datos.astype(int)
    return datos, label_encoders


"""def transformar_datos(datos_nuevos, label_encoders):
    for i in range(datos_nuevos.shape[1]):
        if isinstance(datos_nuevos[0, i], str):
            if label_encoders[i] is not None:
                datos_nuevos[0, i] = label_encoders[i].transform([datos_nuevos[0, i]])[0]
    datos_nuevos = datos_nuevos.astype(int)
    return datos_nuevos"""

ruta_local = "/content/drive/MyDrive/Colab Notebooks/Archivos/solar+flare/flare.data2"

try:
    datos, clase = cargar_datos(ruta_local)
    datos, label_encoders = codificar_datos(datos)
    for j in range(clase.shape[1]):
        if isinstance(clase[0, j], str):
            le = LabelEncoder()
            clase[:, j] = le.fit_transform(clase[:, j])
    clase = clase.astype(int)
except Exception as e:
    print(f"Ocurrió un error al leer el archivo: {e}")

datos_entrena, datos_prueba, clase_entrena, clase_prueba = train_test_split(datos, clase, test_size=0.2)

scaler = StandardScaler()
datos_entrena = scaler.fit_transform(datos_entrena)
datos_prueba = scaler.transform(datos_prueba)

modelo = MultiOutputClassifier(LogisticRegression(max_iter=200))
modelo.fit(datos_entrena, clase_entrena)
np.set_printoptions(suppress=True)

predicción = modelo.predict(datos_prueba)

for col, le in enumerate(label_encoders):
    if le is not None:
        print(f"Columna {col+1} clases: {le.classes_}")

print("Porcentaje de aciertos:", modelo.score(datos_prueba, clase_prueba))
print("\n", predicción)

Columna 1 clases: ['B' 'C' 'D' 'E' 'F' 'H']
Columna 2 clases: ['A' 'H' 'K' 'R' 'S' 'X']
Columna 3 clases: ['C' 'I' 'O' 'X']
Porcentaje de aciertos: 0.8317757009345794

 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [6 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0